version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheddy
    container_name: scheddy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: "npm run start"
